<template><h1 id="form" tabindex="-1"><a class="header-anchor" href="#form" aria-hidden="true">#</a> Form</h1>
<p>使用form组件快速布局</p>
<nav class="table-of-contents"><ul><li><RouterLink to="#cols">Cols</RouterLink></li><li><RouterLink to="#labelposition">LabelPosition</RouterLink></li><li><RouterLink to="#formcolumn清单文件">FormColumn清单文件</RouterLink></li><li><RouterLink to="#formconfig">FormConfig</RouterLink></li><li><RouterLink to="#formcolumn">FormColumn</RouterLink></li><li><RouterLink to="#formevents">FormEvents</RouterLink></li></ul></nav>
<d/>
### 基础用法
<mycode tag="Form/Simple" style="max-width: 850px;"/>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mg-form</span> <span class="token attr-name">:options</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>options<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
  <span class="token keyword">import</span> <span class="token punctuation">{</span> model <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'magic'</span>
  <span class="token keyword">import</span> data <span class="token keyword">from</span> <span class="token string">'./data.js'</span>

  <span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
    <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> <span class="token punctuation">{</span>
        options<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">model<span class="token punctuation">.</span>Form</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
          columns<span class="token operator">:</span> <span class="token punctuation">[</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患内容'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'desc'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Textarea'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患单号'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'number'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Text'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患级别'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'level'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Radio'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'level'</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">'button'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'检查时间'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'date'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Date'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患类别'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Select'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> multiple<span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'整改部门'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'department'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'TreeSelect'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'department'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
          <span class="token punctuation">]</span><span class="token punctuation">,</span>
          events<span class="token operator">:</span> <span class="token punctuation">{</span>
            <span class="token function-variable function">init</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'category'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>category<span class="token punctuation">)</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'level'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>level<span class="token punctuation">)</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'department'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>department<span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token function-variable function">submit</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">form<span class="token punctuation">,</span> done</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              <span class="token function">setTimeout</span><span class="token punctuation">(</span>done<span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
          <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>

</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br></div></div><h3 id="cols" tabindex="-1"><a class="header-anchor" href="#cols" aria-hidden="true">#</a> Cols</h3>
<mycode tag="Form/Cols" style="max-width: 850px;"/>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mg-form</span> <span class="token attr-name">:options</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>options<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
  <span class="token keyword">import</span> <span class="token punctuation">{</span> model <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'magic'</span>
  <span class="token keyword">import</span> data <span class="token keyword">from</span> <span class="token string">'./data.js'</span>
  <span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
    <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> <span class="token punctuation">{</span>
        options<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">model<span class="token punctuation">.</span>Form</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
          config<span class="token operator">:</span> <span class="token punctuation">{</span>
            cols<span class="token operator">:</span> <span class="token number">12</span>
          <span class="token punctuation">}</span><span class="token punctuation">,</span>
          columns<span class="token operator">:</span> <span class="token punctuation">[</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患内容'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'desc'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Textarea'</span><span class="token punctuation">,</span> cols<span class="token operator">:</span> <span class="token number">24</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患单号'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'number'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Text'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患级别'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'level'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Radio'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'level'</span><span class="token punctuation">,</span> type<span class="token operator">:</span> <span class="token string">'button'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'检查时间'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'date'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Date'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患类别'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Select'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> multiple<span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'整改部门'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'department'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'TreeSelect'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'department'</span> <span class="token punctuation">}</span>
          <span class="token punctuation">]</span><span class="token punctuation">,</span>
          events<span class="token operator">:</span> <span class="token punctuation">{</span>
            <span class="token function-variable function">init</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'category'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>category<span class="token punctuation">)</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'level'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>level<span class="token punctuation">)</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'department'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>department<span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token function-variable function">submit</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">form<span class="token punctuation">,</span> done</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              <span class="token function">setTimeout</span><span class="token punctuation">(</span>done<span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token string">'input:category'</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">val</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>val<span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
          <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span>
      <span class="token comment">// console.log(6,this.options)</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>

</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br></div></div><h3 id="labelposition" tabindex="-1"><a class="header-anchor" href="#labelposition" aria-hidden="true">#</a> LabelPosition</h3>
<div class="custom-container warning"><p class="custom-container-title">说明</p>
<p>默认情况下，label的位置位于表单的上方，主要是为了解决label长度不齐整的情况<br/>
在label的名称相对规整情况下，可以设置<code>labelPosition</code>为<code>right</code></p>
</div>
<mycode tag="Form/LabelPosition" style="max-width: 850px;"/>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mg-form</span> <span class="token attr-name">:options</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>options<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
  <span class="token keyword">import</span> <span class="token punctuation">{</span> model <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'magic'</span>
  <span class="token keyword">import</span> data <span class="token keyword">from</span> <span class="token string">'./data.js'</span>

  <span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
    <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> <span class="token punctuation">{</span>
        options<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">model<span class="token punctuation">.</span>Form</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
          config<span class="token operator">:</span> <span class="token punctuation">{</span>
            cols<span class="token operator">:</span> <span class="token number">12</span><span class="token punctuation">,</span>
            labelWidth<span class="token operator">:</span> <span class="token string">'80px'</span><span class="token punctuation">,</span>
            labelPosition<span class="token operator">:</span> <span class="token string">'right'</span>
          <span class="token punctuation">}</span><span class="token punctuation">,</span>
          columns<span class="token operator">:</span> <span class="token punctuation">[</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患内容'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'desc'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Textarea'</span><span class="token punctuation">,</span> cols<span class="token operator">:</span> <span class="token number">24</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患单号'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'number'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Text'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患级别'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'level'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Select'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'level'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'检查时间'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'date'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Date'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'隐患类别'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'Select'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> multiple<span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token punctuation">{</span> label<span class="token operator">:</span> <span class="token string">'整改部门'</span><span class="token punctuation">,</span> field<span class="token operator">:</span> <span class="token string">'department'</span><span class="token punctuation">,</span> layout<span class="token operator">:</span> <span class="token string">'TreeSelect'</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token string">'department'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
          <span class="token punctuation">]</span><span class="token punctuation">,</span>
          events<span class="token operator">:</span> <span class="token punctuation">{</span>
            <span class="token function-variable function">init</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'category'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>category<span class="token punctuation">)</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'level'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>level<span class="token punctuation">)</span>
              <span class="token keyword">this</span><span class="token punctuation">.</span>options<span class="token punctuation">.</span><span class="token function">setSource</span><span class="token punctuation">(</span><span class="token string">'department'</span><span class="token punctuation">,</span> data<span class="token punctuation">.</span>department<span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token function-variable function">submit</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">form<span class="token punctuation">,</span> done</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
              <span class="token function">setTimeout</span><span class="token punctuation">(</span>done<span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
          <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>

</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br></div></div><h3 id="formcolumn清单文件" tabindex="-1"><a class="header-anchor" href="#formcolumn清单文件" aria-hidden="true">#</a> FormColumn清单文件</h3>
<h3 id="formconfig" tabindex="-1"><a class="header-anchor" href="#formconfig" aria-hidden="true">#</a> FormConfig</h3>
<h3 id="formcolumn" tabindex="-1"><a class="header-anchor" href="#formcolumn" aria-hidden="true">#</a> FormColumn</h3>
<h3 id="formevents" tabindex="-1"><a class="header-anchor" href="#formevents" aria-hidden="true">#</a> FormEvents</h3>
</template>
